### ISSUE TITLE
How to use loopback-component-auth with passport-azure-ad

### ISSUE THREAD

**Issue by percenuage** [benkroeger/loopback-component-auth#9]
Hello,

I would like to use loopback with the SAML authentification. I already set up an application (Express only) with [passport-azure-ad@1.4.8](https://github.com/AzureAD/passport-azure-ad/tree/v1.4.8). I have some difficulties to understand the documentation of this component. Could you help me ? Thank you.

**Comment by benkroeger** [comment]
Hi @percenuage,
granted, documentation is not very detailed here. That is mostly due to this module's development being continued on a company-internal repository.
In general, you'd have to implement an `auth-scheme` that wraps your passport strategy into something that this component can understand and then map to what `loopback-component-passport` expects.
